(prelude-require-package 'ag)
(prelude-require-package 'chruby)
(prelude-require-package 'labburn-theme)
(prelude-require-package 'pcre2el)
(prelude-require-package 'moody)
(prelude-require-package 'string-inflection)
